### PR TITLE
Implement eigh and test

### PR DESCRIPTION
**Pull request by HannesHolste**
Output identical to reference.

ref

```
Eigvals 9
0.527576831536  0.380955902485  0.302541529797  0.266409397663  0.255696353121  0.222923562728  0.202538724053  0.191550929645  0.0

Proportion explained    9
0.2244823211    0.162095566209  0.12873049152   0.113356380295  0.108798012753  0.0948532911187 0.0861796048848 0.081504332119  0.0

Species 0   0

Site    9   9
10086.PC.481    -0.0705337512946    -0.0523255833501    0.430931391656  -0.116746630305 0.140169551454  -0.0121985776207    -0.144852652533 0.0708443496647 -0.0
10086.PC.593    -0.15252345786  -0.367119659406 -0.0488310385909    0.286852415403  -0.122137624507 0.0234169453317 -0.141457741587 -0.0529995496517    -0.0
10086.PC.356    -0.310268662031 0.202957439323  -0.161995239726 -0.0244935105553    0.15035822631   -0.249882413934 -0.0749673365754    -0.147145848302 -0.0
10086.PC.355    -0.181535837645 0.280265981912  -0.0544393413007    0.0939578745749 0.0589143460999 0.352680352153  0.0046686377854 0.0329116944137 -0.0
10086.PC.354    -0.306665965365 -0.0701963718488    0.0407228466959 -0.1114824179   -0.201732274725 -0.0620072371812    0.284898055936  0.114474970493  -0.0
10086.PC.636    0.305648978048  0.0979331334515 -0.0703076036076    0.203718428091  0.0923240786186 -0.145946437069 0.0358828025594 0.269537748495  -0.0
10086.PC.635    0.226649045655  0.135140021056  -0.0831332541419    -0.198963114956 -0.313113479926 -0.000656969485293  -0.195494992339 0.00207851498269    -0.0
10086.PC.607    0.168428915044  -0.293927672225 -0.214003498911 -0.237780522122 0.217479735297  0.101065266217  0.0505607098618 -0.0158839896734    -0.0
10086.PC.634    0.320800735448  0.0672727110869 0.161055737927  0.10493747777   -0.022262558621 -0.00647092841082   0.180762516892  -0.273817890423 -0.0

Biplot  0   0

Site constraints    0   0
```

output

```
Eigvals 8
0.527576831536  0.380955902485  0.302541529797  0.266409397663  0.255696353121  0.222923562728  0.202538724053  0.191550929645

Proportion explained    8
0.2244823211    0.162095566209  0.12873049152   0.113356380295  0.108798012753  0.0948532911187 0.0861796048848 0.081504332119

Species 0   0

Site    9   8
10086.PC.481    -0.0705337512946    0.0523255833501 0.430931391656  -0.116746630305 0.140169551454  -0.0121985776207    -0.144852652533 0.0708443496647
10086.PC.593    -0.15252345786  0.367119659406  -0.0488310385909    0.286852415403  -0.122137624507 0.0234169453317 -0.141457741587 -0.0529995496517
10086.PC.356    -0.310268662031 -0.202957439323 -0.161995239726 -0.0244935105553    0.15035822631   -0.249882413934 -0.0749673365754    -0.147145848302
10086.PC.355    -0.181535837645 -0.280265981912 -0.0544393413007    0.0939578745749 0.0589143460999 0.352680352153  0.0046686377854 0.0329116944137
10086.PC.354    -0.306665965365 0.0701963718488 0.0407228466959 -0.1114824179   -0.201732274725 -0.0620072371812    0.284898055936  0.114474970493
10086.PC.636    0.305648978048  -0.0979331334515    -0.0703076036076    0.203718428091  0.0923240786186 -0.14594643707  0.0358828025594 0.269537748495
10086.PC.635    0.226649045655  -0.135140021056 -0.0831332541419    -0.198963114956 -0.313113479926 -0.000656969485293  -0.195494992339 0.00207851498268
10086.PC.607    0.168428915044  0.293927672225  -0.214003498911 -0.237780522122 0.217479735297  0.101065266217  0.0505607098618 -0.0158839896734
10086.PC.634    0.320800735448  -0.0672727110869    0.161055737927  0.10493747777   -0.022262558621 -0.00647092841081   0.180762516892  -0.273817890423

Biplot  0   0

Site constraints    0   0

```

### CODE REVIEW

**Comment by antgonza** [comment]
@HannesHolste conflicts, can you resolve?

**Comment by HannesHolste** [comment]
Resolved conflicts, rebased and force pushed. Ready @antgonza.

**Comment by antgonza** [comment]
Looks good but could you add something like [.coveragerc](https://github.com/biocore/qiita/blob/master/.coveragerc)? I just activated coveralls so the next push should run it. This should close: https://github.com/biocore/mds-approximations/issues/3 

Also, could you add an issue about testing the actual resulting values of the methods vs. just testing their shape? 

Thanks!

**Comment by HannesHolste** [comment]
Good idea. Issue opened at #30.

Coveralls #32.

Ready to merge.

**Comment by ElDeveloper** [comment]
👍

**Pull request merged**
