### PR TITLE
Clean up test datasets

### PR DESCRIPTION
**Pull request by HannesHolste**
There were two data directories and one duplicate dataset, which was confusing.

### CODE REVIEW

**Comment by antgonza** [comment]
@HannesHolste, something is broken with the tests, could you take a look? Thanks!

**Comment by HannesHolste** [comment]
@antgonza: no errors, travis just timed out. Can you re-trigger it? I couldn't see a way to do it, I don't think I have access

**Comment by antgonza** [comment]
Restarted the job and it failed again ... my guess there is an issue with the environment.yml, have you tested locally in the last few days? Anyway, restarted again, just in case ...

**Comment by HannesHolste** [comment]
@antgonza travis issues should be fixed after #46 is merged and I rebase from master.

**Comment by antgonza** [comment]
@HannesHolste I have restarted multiple times these tests without success, if they fail again, could you pull from master and push this branch again? Thanks!

**Pull request merged**
