### PR TITLE
FSVD performance & accuracy improvements

### PR DESCRIPTION
**Pull request by HannesHolste**
@wasade and/or @antgonza please review.

Incorporated Daniel's suggested performance enhancements for square, symmetric distance matrices as input:

- remove matrix transposes
- add centering step

fsvd now raises an error if matrix is not square.

### CODE REVIEW

**Review by antgonza — APPROVED** [review]

**Comment by antgonza** [comment]
The code looks good but note that there are errors, seem flake8. @HannesHolste could you fix?

**Comment by wasade** [comment]
I think this is fine. Two questions: should the in place e and f matrix calls be used as for large distance matrices this csn be important? Second, should the centering be applied to the other algorithms in this repository?

**Comment by HannesHolste** [comment]
@wasade: 

1. good catch on the e_matrix and f_matrix optimizations you made. I erroneously assumed they were incorporated into `skbio.stats.ordination._utils`. I will add that code back into the fsvd.py file. 

In addition, will you submit a PR to add the optimized f_matrix and e_matrix to skbio?

2. Yes, seems like centering should be applied to the other algorithms to be consistent. I can do that.

@antgonza fixed, flake8 passes now.

**Comment by wasade** [comment]
Thanks! I'm not sure how best to integrate the in place operations into
skbio as it does represent an API change. Open to suggestions

**Comment by antgonza** [comment]
I think we can leave them here for now and when we move the code to skbio we can replace those implementations ...

**Comment by antgonza** [comment]
@HannesHolste, want me to merge this PR or do you want to add the centering to the other methods here (vs another PR)?

**Comment by HannesHolste** [comment]
Yep, feel free to merge.

A habit from industry I’ve adopted is keeping PRs smaller so review is
easier.

**Pull request merged**
