### PR TITLE
Fix eigenvector dimensionality reduction

### PR DESCRIPTION
**Pull request by HannesHolste**
Patching previous PR #24 .

I fixed two mistakes that empirical testing revealed:
1. Forgot to convert to numpy array
2. Incorrectly sliced unwanted dimensions off array of eigenvectors

### CODE REVIEW

**Comment by antgonza** [comment]
I think these changes could have been push to the previous PR, right? But perhaps I'm missing something. Anyway, could you close this PR and commit these changes to the previous one?

**Comment by HannesHolste** [comment]
Unfortunately I already closed and merged the previous PR, so there's no way to merge this commit into the previous PR without rebasing the master branch history (which I could do only if nobody else has a copy of this codebase on their computer, because it'll mess up their history).

**Comment by antgonza** [comment]
But these changes are also included (or could be included) here: https://github.com/biocore/mds-approximations/pull/26, right?

**Comment by HannesHolste** [comment]
Ah, right. That works.

**Pull request closed without merging**
