### PR TITLE
PCoA updates

### PR DESCRIPTION
**Pull request by HannesHolste**
This PRs brings this repo in sync with changes made for https://github.com/biocore/scikit-bio/pull/1569 

1. Don't normalize eigenvectors to unit length (doesn't change correctness of results anyway, just rescaling)
2. Compute proportions explained via eigenvalues obtained by matrix trace. For details see notes on code changes in https://github.com/biocore/scikit-bio/pull/1569

### CODE REVIEW

**Comment by antgonza** [comment]
Just to be sure, this implies that the same code is in skbio and this repo, right? If that's the case, will it be better to erase the code from here and use skbio's?

**Comment by HannesHolste** [comment]
@antgonza: Correct. Good suggestion, and I think it's best to do so at a later date, _after_ the FSVD is merged into fsvd. I'd just like to get this repo up to speed with Rob's requirements to have all work public for now.

**Comment by antgonza** [comment]
My suggestion is to focus in addressing all the issues in https://github.com/biocore/scikit-bio/pull/1569 so it can be merge and then continue with this.

**Comment by HannesHolste** [comment]
FSVD is now part of skbio. Perhaps just remove 'raw' fsvd code from this repo completely, and replace with a call to skbio's fsvd?

**Comment by antgonza** [comment]
Replacing sounds great!! Thanks

**Comment by HannesHolste** [comment]
@antgonza fixed travis issues and completed this PR. Had to upgrade miniconda and python (to 3.x), because skbio requires py3 now. 

Edit: I tested this locally with a new conda environment and all tests pass. But travis CI on here keeps failing, and I don't see obvious reasons why. Do you have any suggestions? I'm a bit stuck with debugging this.

**Comment by antgonza** [comment]
@HannesHolste, there are still build errors ... do you want me to try to fix?

**Comment by HannesHolste** [comment]
@antgonza yes I need your input on this, I'm stuck on why this isn't working on travis. I don't see anything blatantly wrong with the config. Tried clean conda env and all tests pass locally...

**Comment by antgonza** [comment]
OK, will take a look later today, thanks!

**Comment by antgonza** [comment]
Finally was able to get back to this, sorry for the delay. Anyway, a couple of notes:
- We are trying to settle all software on Python 3.6
- It looks like you are creating a branch on the biocore repo and on yours and then doing a PR; while IMOO it will be better if you only created a new branch in your repo and did a PR - happy to chat if you have questions about this, just DM.

**Pull request merged**
