### PR TITLE
WIP: Cogent porrt

### PR DESCRIPTION
**Pull request by mortonjt**
Here's a complete port over of both `scmds` and `nystrom` from pycogent.

I haven't included numpy docs for `approximate_mds.py` or `goodness_of_fit.py`.  Do we really care?

Here, I created a really barebone wrapper function for `scmds` and `nystrom`, to make standardizing these function calls more straightforward.

### CODE REVIEW

**Comment by mortonjt** [comment]
Also, would anyone opposed to making skbio a dependency?  I personally like some of the testing utils.

**Comment by antgonza** [comment]
fine with me.

**Comment by ElDeveloper** [comment]
Fine with me as well.

**Comment by mortonjt** [comment]
:boom: Tests passing

**Comment by antgonza** [comment]
I think the code looks fine, note that this has been reviewed a few times before. However, it's not skbio ready but I think we shouldn't spend time on this and simply benchmark, then clean the code that is actually gonna be moved to skbio. Thus, merging.

**Pull request merged**
